### ISSUE TITLE
http error too many requests

### ISSUE THREAD

**Issue by NaveenBen** [adnane-X-tebbaa/GRecon#4]
[>] Looking in Pasting Sites...
Traceback (most recent call last):
  File "/mnt/c/Users/r00t/Desktop/tool/GRecon/grecon.py", line 139, in <module>
    from plugins import pasting
  File "/mnt/c/Users/r00t/Desktop/tool/GRecon/plugins/pasting.py", line 31, in <module>
    for gamma in search(query, tld=zolo, num=30 , stop=60 , pause=2):
  File "/home/r00t/.local/lib/python3.9/site-packages/googlesearch/__init__.py", line 305, in search
    html = get_page(url, user_agent, verify_ssl)
  File "/home/r00t/.local/lib/python3.9/site-packages/googlesearch/__init__.py", line 174, in get_page
    response = urlopen(request)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 555, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 747, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by adnane-X-tebbaa** [comment]
Google ip Block! just change your ip or use a VPN while using the script

**Comment by DEMON1A** [comment]
- I think this issue could be fixed by adding more TLDs to the TLD list and keep switching between them after every search and removing the main delay in the middle of the code and replace it with 6-10 sec between every google search, I edited my local version and it seems to be finer with the block with this way but it requires more time running the script. to collect more google TLDs use this:
```
site: google.com.*
```
